### ISSUE TITLE
I don't understand the on board RGB led

### ISSUE THREAD

**Issue by RichardFerraro** [makerdiary/nrf52840-mdk-usb-dongle#1]
I am able to program the board just fine.

I do not understand the on board leds at P0.22 P0.23 P0.24 (I suspect it is 0.24)

Are they LEDS_ACTIVE_STATE 1 ?

**Comment by caizelin** [comment]
> I am able to program the board just fine.
> 
> I do not understand the on board leds at P0.22 P0.23 P0.24 (I suspect it is 0.24)
> 
> Are they LEDS_ACTIVE_STATE 1 ?

@RichardFerraro Here is the schematic of RGB LED. It means that GREEN LED is connected to P0.22, RED LED is connected to P0.23 and BLUE LED is connected to P0.24. The `LEDS_ACTIVE_STATE` should be set to `0`.
<img width="540" alt="screen shot 2018-12-11 at 4 57 37 pm" src="https://user-images.githubusercontent.com/37929607/49789133-31df2800-fd66-11e8-8e37-f89eb1f3833d.png">

**Comment by caizelin** [comment]
I’m closing this issue because it has been inactive for a long time. Please reopen if you still encounter this issue.
Thank you!
