### ISSUE TITLE
Dongle not entering boot mode after flashin blinky.hex and not detected as serial port as well

### ISSUE THREAD

**Issue by bhanuprakash3242** [makerdiary/nrf52840-mdk-usb-dongle#15]
Dongle not entering boot mode after flashing blinky.hex and not detected as serial port as well
nRF52840-MDK USB dongle

**Comment by caizelin** [comment]
> Dongle not entering boot mode after flashing blinky.hex and not detected as serial port as well
> nRF52840-MDK USB dongle

@bhanuprakash3242 which `blinky.hex` are you flashed? The application address must start after MBR. That is, the `blinky.hex` should start at `0x1000` address.

**Comment by alexcode9** [comment]
same thing happened to me, copied a hex after uf2conv and now the dongle is lost... it just blinks red two times if button pressed

**Comment by caizelin** [comment]
Solved! Will close for now.
