### ISSUE TITLE
flashing dongle

### ISSUE THREAD

**Issue by pabloopez** [makerdiary/nrf52840-mdk-usb-dongle#17]
I have been in the openSK documentation on GitHub that there is need for an special propietary device to flash de dongle. Is that right? Isn't it possible to flash it by usb? Thanks!

**Comment by caizelin** [comment]
> I have been in the openSK documentation on GitHub that there is need for an special propietary device to flash de dongle. Is that right? Isn't it possible to flash it by usb? Thanks!

Hi,
Our nRF52840 MDK USB Dongle contains a bootloader, so it can be flashed via usb and no other special propietary device needed.
Please follow this guide to getting started: [Getting Started with OpenSK](https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/opensk/getting-started/)

**Comment by caizelin** [comment]
I’m closing this issue because it has been fixed. Please reopen if you still encounter this issue.
Thank you!
