### ISSUE TITLE
Where to find uf2conv.py

### ISSUE THREAD

**Issue by abuckton** [makerdiary/nrf52840-mdk-usb-dongle#20]
I have a new MDK that came with the UF2 boot loader (took me a while to work that out ... there really should be documentation to say that it's changed).

When I look how to do DFU using UF2 (https://github.com/makerdiary/nrf52840-mdk-usb-dongle/tree/master/firmware/uf2_bootloader) it mentioned uf2conv.py.
Where is that script? (It is not on the link "[Python Conversion Script](https://github.com/makerdiary/nrf52840-mdk-usb-dongle/tree/master/tools)" 

Thanks,
Anthony

**Comment by abuckton** [comment]
As an interim, I've found the Microsoft version of the script: https://github.com/Microsoft/uf2/blob/master/utils/uf2conv.py and pasted it into /usr/local/bin
 It seemed to work as I now have my Thread boarder router talking to wpantund and wpanctl

**Comment by caizelin** [comment]
> As an interim, I've found the Microsoft version of the script: https://github.com/Microsoft/uf2/blob/master/utils/uf2conv.py and pasted it into /usr/local/bin
> It seemed to work as I now have my Thread boarder router talking to wpantund and wpanctl

@abuckton That's okay! The script is ignored by the `.gitignore` file, and I have just fixed it. This script is also hosted in the [tools](https://github.com/makerdiary/nrf52840-mdk-usb-dongle/tree/master/tools) directory.
