### ISSUE TITLE
Can't get "usbd_cdc_acm" example working on the MDK USB Dongle

### ISSUE THREAD

**Issue by aeozyalcin** [makerdiary/nrf52840-mdk-usb-dongle#21]
Hello! 

I am trying to get virtual COM port working on the MDK USB dongle in hopes of using this feature in a more involved project to provide debug info.

I am trying to compile and get the USBD_CDC_ACM example working, my understanding is that this example creates a virtual comport over USB, and allows the nRF52840 to talk to the host PC via serial.

I tried getting this example working 2 different ways, but neither one worked. 

- I tried building the Nordic example from scratch as it was provided in the 15.0 SDK. I got the example to compile and build fine, but when I flash it to the dongle, I don't see a COM port opened on my host PC (Windows 10).
- I built the example that's already provided in the nrf52840-mdk repository, and flashed it to the dongle. Only change I had to was in the linker file, to move the flash start position from 0x0 to 0x1000., which I also had to do for the first method. I had the same result as before, the device did not enumerate as a COM port on my host pc.

@caizelin I hope you can help out here! Thank you to everyone in advance!

**Comment by caizelin** [comment]
nRF5 SDK is migrated to nRF Connect SDK. You can try the hello world sample that using USB CDC ACM to print message: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/guides/ncs/samples/hello_world/
Will close for now, and if you still have any question, please consider re-opening it.
