### ISSUE TITLE
Blinky .hex does not work

### ISSUE THREAD

**Issue by oschade** [makerdiary/nrf52840-mdk-usb-dongle#22]
Hello,

i can't make the blinky example run on my nrf52840 mdk usb dongle.
I followed the tutorial at:

https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/nrf5-sdk/
and
https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/programming/

I compiled one blinky example by myself, but neither this one nor the one from this repository can be transfer to the usb dongle. Please see the picture below:

![blinky app does not work](https://user-images.githubusercontent.com/19870969/76166244-7ae67d80-615d-11ea-89da-533a8e772a19.png)

Where is the problem? I was able to transfer a soft device and the ble blinky example. But this doesn't show any ble signal in my smartphone. What am I doing wrong?

**Comment by caizelin** [comment]
@oschade Please check the `blinky_gcc_nrf52.ld` file to make sure using the right memory regions:
```
MEMORY
{
  FLASH (rx) : ORIGIN = 0x1000, LENGTH = 0xff000
  RAM (rwx) :  ORIGIN = 0x20000008, LENGTH = 0x3fff8
}
```

**Comment by oschade** [comment]
Cool, now it works! Thank you!
