### ISSUE TITLE
How to connect to Jtag ?

### ISSUE THREAD

**Issue by ToutUnProg** [makerdiary/nrf52840-mdk-usb-dongle#24]
Hi,

I wanted to flash the firmware to put TockOS into the nrf52840-mdk-usb-dongle by using a JTag probe.
I build a card to connect the usb jtag probe to the dongle and connect everything as it is in the attached scheme.
![Cable_JTAG_IDC](https://user-images.githubusercontent.com/46676633/77163323-1fe24e00-6aae-11ea-9fdb-e6ab13d4904b.jpg)

Is there something wrong ? can you help me please.

**Comment by caizelin** [comment]
@ToutUnProg It's right. You can do this.

**Comment by ToutUnProg** [comment]
OK, I did this on a little Card. But it does not work.
Is there a process to power up the JTag and the dongle that I cannot find ?
![IMG_20200321_095132](https://user-images.githubusercontent.com/46676633/77223014-fc281200-6b58-11ea-80bf-64f0496891bc.jpg)
![IMG_20200321_095139](https://user-images.githubusercontent.com/46676633/77223015-fd593f00-6b58-11ea-8ffc-19322be15c1c.jpg)
![IMG_20200321_095145](https://user-images.githubusercontent.com/46676633/77223020-1104a580-6b59-11ea-838f-2b46549017df.jpg)

**Comment by caizelin** [comment]
See this guide that may help: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/hardware/#debug-interface
Will close for now, and if you still have any questions, please consider re-opening it.
