### ISSUE TITLE
nRF52840 MDK USB Dongle question

### ISSUE THREAD

**Issue by Brechen** [makerdiary/nrf52840-mdk-usb-dongle#25]
Hello, can I use this device directly on my Mac? I want to use it as an Ant+ transmitter. Do I have to program it or can be used on the go? Many thanks

**Comment by caizelin** [comment]
> Hello, can I use this device directly on my Mac? I want to use it as an Ant+ transmitter. Do I have to program it or can be used on the go? Many thanks

@Brechen You can use this device on macos. Here is the guide you can follow to program this dongle: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/programming/

**Comment by caizelin** [comment]
There was no response for a long time. Will close for now, and if you still have trouble with it, please consider re-opening this issue.
