### ISSUE TITLE
ble 5.0 sniffer 

### ISSUE THREAD

**Issue by Pillar1989** [makerdiary/nrf52840-mdk-usb-dongle#37]
@caizelin  @xiongyihui A BLE 5.0 sniffer is badly needed.

**Comment by xiongyihui** [comment]
Try this one https://github.com/makerdiary/raccoon

**Comment by Pillar1989** [comment]
@xiongyihui  support extend packets ?

**Comment by gbuzogany** [comment]
I got the Nordic BLE sniffer working on the nrf52840-MDK, it works well with wireshark and seems to be very complete.
Download here:
https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Sniffer-for-Bluetooth-LE/Download#infotabs

Then follow the instructions here to get it working:
https://infocenter.nordicsemi.com/pdf/nRF_Sniffer_UG_v2.2.pdf

**Comment by caizelin** [comment]
@gbuzogany Awesome!

**Comment by gbuzogany** [comment]
It was on the MDK USB dongle (https://makerdiary.com/collections/frontpage/products/nrf52840-mdk-usb-dongle).

I used the sniffer_nrf52840dongle_nrf52840_7cc811f.hex

**Comment by telethonic** [comment]
Thanks for the quick reply :-)

I'm getting closer, but not quite there yet. 

I wrote that firmware using nRF Connect,
put the extcap/* files in place,
and the snifffer shows up in wireshark.

When I start a capture though, wireshark just hangs :-|

Is there a way to check if the dongle was flashed correctly? 
Did you maybe use a different tool to flash it? (@gbuzogany )

**Comment by gbuzogany** [comment]
I used a segger j-link to flash the board (SWD interface).
I use macOS.

Make sure to follow the installation guide:
https://infocenter.nordicsemi.com/pdf/nRF_Sniffer_UG_v2.2.pdf
