### ISSUE TITLE
nrf52840 not found in USB Device Tree MacOS Mojave v10.14

### ISSUE THREAD

**Issue by alnjxn** [makerdiary/nrf52840-mdk-usb-dongle#4]
Hello
Have just gone through the wpantund installation guide using Hombrew on MacOS. Have the service started as a dameon:

```
Name           Status  User Plist
dbus           started root /Users/ajackson/Library/LaunchAgents/homebrew.mxcl.dbus.plist
```

Plugged the USB device into two different USB hubs and neither show the device in the device tree. 
<img width="863" alt="screen shot 2019-02-12 at 10 53 33 am" src="https://user-images.githubusercontent.com/1423708/52660414-78f7af80-2eb4-11e9-9ebb-586495df3e6e.png">

There are no LED's on either of the two USB dongles i purchased. When plugged into Mac. However when I plug into RaspberryPi (Plan to use 2nd device for border router) I at least get a blue LED.

**Comment by caizelin** [comment]
@alnjxn When plugged into Mac, was the USB power indicator(Green LED on the dongle) lighting up?
Pls check the connection to ensure if the dongle is powered up correctly.

**Comment by alnjxn** [comment]
@caizelin seems that the dongle was not seated properly in the hub. Green light is on and I can now see the device in the tree. Sorry for not properly checking that prior to posting. Thanks for the quick reply.
