### ISSUE TITLE
Green Solid LED When In Programming Mode

### ISSUE THREAD

**Issue by matt001k** [makerdiary/nrf52840-mdk-usb-dongle#52]
My LED stays green and both the nrfutil and NRF Connect programmer cannot find the chip. The NRF Connect app says the device is unsupported.
![image](https://user-images.githubusercontent.com/61891357/107601728-81933580-6bf5-11eb-9779-6787f2bb9740.png)

**Comment by mkotzjan** [comment]
Same for me

**Comment by mkotzjan** [comment]
Same for me. But it appears as a flash drive which, according to the [wiki](https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/programming/#dfu-via-uf2-bootloader), means that it's using the UF2 Bootloader

**Comment by chuckixia** [comment]
this is happening for me too. I would like to use the original NRF Connect tool instead. How do I downgrade or change the bootloader to use the old one?
