### ISSUE TITLE
No access to bootloader

### ISSUE THREAD

**Issue by TorstenRobitzki** [makerdiary/nrf52840-mdk-usb-dongle#8]
Hi,
I have some (3) new nRF52840 MDK USB Dongle, with cases. When I connect them to my PC (OS/X 10.14.6) and start nRF Connect, I can select the connected device and get some device informations but I will not get the chance to flash them (looks like the nRF Connect is still busy to interrogate the connected device:

<img width="918" alt="Bildschirmfoto 2019-07-25 um 17 49 19" src="https://user-images.githubusercontent.com/2026114/61889458-bcdfed80-af05-11e9-86ca-57a44ccbac05.png">

If I connect a PCA10059, nRF Connect can get all required informations from the device:

<img width="603" alt="Bildschirmfoto 2019-07-25 um 17 53 33" src="https://user-images.githubusercontent.com/2026114/61889534-e39e2400-af05-11e9-8c47-f8000fc98029.png">

I'm using nRF Connect version 3.0.0. I have tried two of the 3 USB Dongles, both have this issue.

**Comment by caizelin** [comment]
@TorstenRobitzki 
Hi,
To program the Dongle, it must be in bootloader mode. While holding the dongle's RESET/USR button, connect it to your computer. When the Dongle has entered the bootloader mode, the RGB LED pulses RED. The Dongle is now ready for programming.

You can also check out the programming tutorial here: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/programming/

**Comment by TorstenRobitzki** [comment]
Thanks, works like a charm!
