### ISSUE TITLE
Problem after programming Blinky from nRF Connect SDK

### ISSUE THREAD

**Issue by ajlennon** [makerdiary/nrf52840-mdk-usb-dongle#87]
Hi,

I am getting going with the MDK USB dongle... I managed to run the Makerdiary Blinky app and the BLE Blinky app successfully.

I want to look at Bluetooth Mesh so I then moved onto looking at the Nordic nRF Connect SDK building the Zephyr Blinky app within VSCode with nRFConnect extensions.

I got the build output converted to .uf2 and dragged and dropped this to program with the UF2 bootloader and the LED blinks as expected. So far so good....

However when I now insert the dongle with the reset button pressed it doesn't go into the UF2 bootloader mode any more. Instead it drops into the blinky application.

So I suspect that by programming the nRF Connect SDK example I have wiped out the bootloader?

Can you give me some idea of how to reset the dongle so I can program it again?

Thanks!

**Comment by caizelin** [comment]
@ajlennon NCS examples are provided now, which can work with UF2 Bootloader. Just checkout here: https://wiki.makerdiary.com/nrf52840-mdk-usb-dongle/guides/ncs/
